export const items = [
    {
        id: '1c',
        img: 'shop-images/1c.png',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '2c',
        img: 'shop-images/2c.png',
        name: 'Espresso Dolce',
        reviews: '8',
        price: '8.30$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '3c',
        img: 'shop-images/3c.png',
        name: 'House Blend',
        reviews: '3',
        price: '7$',
        weight: '250g',
        category: 'coffee',
    },
    {
        id: '4c',
        img: 'shop-images/4c.png',
        name: 'Caffe Crema',
        reviews: '10',
        price: '11.30$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '5c',
        img: 'shop-images/5c.png',
        name: 'French Vanilla',
        reviews: '2',
        price: '9.30$',
        weight: '250g',
        category: 'coffee',
    },
    {
        id: '6c',
        img: 'shop-images/6c.png',
        name: 'Guatemala Antigua',
        reviews: '15',
        price: '11.60$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '1t',
        img: 'shop-images/1t.png',
        name: 'Ceylon',
        reviews: '12',
        price: '6.20$',
        weight: '240g',
        category: 'tea',
    },
    {
        id: '2t',
        img: 'shop-images/2t.png',
        name: 'Earl Grey',
        reviews: '13',
        price: '5.60$',
        weight: '100g',
        category: 'tea',
    },
    {
        id: '3t',
        img: 'shop-images/3t.png',
        name: 'Vital Rooibos',
        reviews: '3',
        price: '6.70$',
        weight: '300g',
        category: 'tea',
    },
    {
        id: '4t',
        img: 'shop-images/4t.png',
        name: 'Yerba Mate',
        reviews: '20',
        price: '9.30$',
        weight: '150g',
        category: 'tea',
    },
    {
        id: '5t',
        img: 'shop-images/5t.png',
        name: 'Green Tea',
        reviews: '8',
        price: '8.20$',
        weight: '110g',
        category: 'tea',
    },
    {
        id: '6t',
        img: 'shop-images/6t.png',
        name: 'White Tea',
        reviews: '7',
        price: '7$',
        weight: '130g',
        category: 'tea',
    },
    {
        id: '1m',
        img: 'shop-images/1m.png',
        name: 'Love Cofove Mug',
        reviews: '1',
        price: '10.30$',
        capacity: '330ml',
        category: 'mugs',
    },
    {
        id: '2m',
        img: 'shop-images/2m.png',
        name: 'Pink Beans Mug',
        reviews: '3',
        price: '11.10$',
        capacity: '380ml',
        category: 'mugs',
    },
    {
        id: '3m',
        img: 'shop-images/3m.png',
        name: 'Good Morning Mug',
        reviews: '7',
        price: '6.90$',
        capacity: '200ml',
        category: 'mugs',
    },
    {
        id: '4m',
        img: 'shop-images/4m.png',
        name: 'Black&White Mug',
        reviews: '10',
        price: '11.30$',
        capacity: '350ml',
        category: 'mugs',
    },
    {
        id: '5m',
        img: 'shop-images/5m.png',
        name: 'Hedgehog Mug',
        reviews: '14',
        price: '12.20$',
        capacity: '480ml',
        category: 'mugs',
    },
    {
        id: '6m',
        img: 'shop-images/6m.png',
        name: 'Fast Coffee Mug',
        reviews: '20',
        price: '9.90$',
        capacity: '300ml',
        category: 'mugs',
    },
    {
        id: '1a',
        img: 'shop-images/1a.png',
        name: 'Coffee Grinder',
        reviews: '23',
        price: '25.80$',
        unit: "60g of beans",
        category: 'accessories',
    },
    {
        id: '2a',
        img: 'shop-images/2a.png',
        name: 'Electric Water Kettle',
        reviews: '123',
        price: '38.90$',
        unit: "1.7l",
        category: 'accessories',
    },
    {
        id: '3a',
        img: 'shop-images/3a.png',
        name: 'Metal Straws',
        reviews: '0',
        price: '5$',
        unit: "4pcs",
        category: 'accessories',
    },
    {
        id: '4a',
        img: 'shop-images/4a.png',
        name: 'Milk Foamer',
        reviews: '15',
        price: '20.60$',
        unit: "1pcs",
        category: 'accessories',
    },
    {
        id: '5a',
        img: 'shop-images/5a.png',
        name: 'Paper Filters',
        reviews: '1',
        price: '5.60$',
        unit: "100pcs",
        category: 'accessories',
    },
    {
        id: '6a',
        img: 'shop-images/6a.png',
        name: 'Tea Brewer',
        reviews: '7',
        price: '3.80$',
        unit: "1pcs",
        category: 'accessories',
    }
]

//localStorage.setItem('basket', JSON.stringify([['1', 3], ['2', 1], ['3', 10]]))

//const itemsInBasket = localStorage.getItem('basket')

// swtorzyć produkty za pomocą js / do basketa localstorage / map i filter! metody array