export const items = [
    {
        id: '1c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '2c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '3c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '4c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '5c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '6c',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'coffee',
    },
    {
        id: '1t',
        img: 'shop-images/test.jpg',
        name: 'Ceylon',
        reviews: '12',
        price: '6.20$',
        weight: '240g',
        category: 'tea',
    },
    {
        id: '2t',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'tea',
    },
    {
        id: '3t',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'tea',
    },
    {
        id: '4t',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'tea',
    },
    {
        id: '5t',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'tea',
    },
    {
        id: '6t',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        weight: '500g',
        category: 'tea',
    },
    {
        id: '1m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '2m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '3m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '4m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '5m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '6m',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        capacity: '500ml',
        category: 'mugs',
    },
    {
        id: '1a',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        unit: "",
        category: 'accessories',
    },
    {
        id: '2a',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        unit: "",
        category: 'accessories',
    },
    {
        id: '3a',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        unit: "",
        category: 'accessories',
    },
    {
        id: '4a',
        img: 'shop-images/test.jpg',
        name: 'Colombian Roast',
        reviews: '6',
        price: '9.90$',
        unit: "",
        category: 'accessories',
    }
]

//localStorage.setItem('basket', JSON.stringify([['1', 3], ['2', 1], ['3', 10]]))

//const itemsInBasket = localStorage.getItem('basket')

// swtorzyć produkty za pomocą js / do basketa localstorage / map i filter! metody array